export const ANALYTICS_EVENTS = {
  DISCART_CHAT_MESSAGE_MANAGEMENT: "CLICK_ARQUIVAR_CONVERSA_TELA_GESTAO",
  DISCART_CHAT_RENDER_CHAT: "CLICK_ARQUIVAR_CONVERSA_TELA_MSGS",
  TEMPLATE_MOST_USED: "CLICK_TOP_2_MODELO_MSG",
  TEMPLATE_LIST: "CLICK_FORA_TOP_2_MODELO_MSG"
};
