export const ANALYTICS_EVENTS = {
  DISCART_CHAT_MESSAGE_MANAGEMENT: "CLICK_ARQUIVAR_CONVERSA_TELA_GESTAO",
  DISCART_CHAT_RENDER_CHAT: "CLICK_ARQUIVAR_CONVERSA_TELA_MSGS",
  MOST_USED: "Mais usadas nos últimos 45 dias",
  TEMPLATE_LIST: "Lista de modelos"
};
