export const COMPONENT_LOCATION = {
  UNREAD: "UNREAD",
  CHAT: "CHAT",
  MESSAGE_MANAGEMENT: "MESSAGE_MANAGEMENT",
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  MESSAGE_SUGESTION: "MESSAGE_SUGESTION",
};
