export const COMPONENT_VIEW = {
  COMPONENT_INIT: "COMPONENT_INIT",
  CHAT_MESSAGES: "CHAT_MESSAGES",
  MESSAGE_MANAGEMENT: "MESSAGE_MANAGEMENT",
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  CONNECTION_ERROR: "CONNECTION_ERROR",
};
